config/routes.rb
Rails.application.routes.draw do
  get 'badges/index'
  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: {
               sessions: 'users/sessions', only: %i[create]
             }

  root to: 'tests#index'

  resources :feedback, only: %i[new create show]
  resources :badges, only: :index
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :badges
    resources :gists, only: %i[index]
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: %i[index] do
        resources :answers, shallow: true, except: %i[index]
      end
    end
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :users_badges, dependent: :destroy
  has_many :users, through: :users_badges, dependent: :destroy
  has_many :badges_rules
  has_many :rules, through: :badges_rules

  validates :name, presence: true
  validates :url, presence: true
  validates :description, presence: true
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[edit update destroy show]

  def index
    @badges = Badge.all
  end

  def show; end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badge_path(@badge)
    else
      render :new
    end
  end

  def edit; end

  def new
    @badge = Badge.new
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    flash[:notice] = 'Deleted successfully'

    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge)
          .permit(:name, :description, :url, rule_ids: [])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges_received = current_user.badges.distinct
    @badges_not_received = Badge.where.not(id: @badges_received.pluck(:id))
  end
end

app/helpers/admin/badges_helper.rb
module Admin::BadgesHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
  def form_badge_header(badge)
    "#{badge.persisted? ? 'Edit' : 'Create new'} badge"
  end

  def print_badge_rules(badge)
    badge.rules
         .map(&:description)
         .join(', ')
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <th class="align-middle" scope="row">
    <%= badge.name  %>
  </th>
  <th class="align-middle" scope="row">
    <%= image_tag(badge.url, size: '25x25') %>
  </th>
  <th class="align-middle" scope="row">
    <%= badge.description  %>
  </th>
  <th class="align-middle" scope="row">
    <%= print_badge_rules(badge) %>
  </th>
  <th class="align-middle" scope="row">
    <%= link_to t('.show'), admin_badge_path(badge) %>
    <%= link_to t('.edit'), edit_admin_badge_path(badge) %>
    <%= link_to t('.delete'),
                admin_badge_path(badge),
                method: :delete,
                data: {
                  confirm: t('.confirmation')
                }    %>
  </th>
</tr>

app/views/admin/badges/_badges_table.erb
<% if resource.empty? %>
  <p><%= t('.no_badges') %></p>
<% end %>
<table  class="table table-hover">
  <tr>
    <th class="align-middle" scope="col">
      <%= t('.name') %>
    </th>
    <th class="align-middle" scope="col">
      <%= t('.icon') %>
    </th>
    <th class="align-middle" scope="col">
      <%= t('.description') %>
    </th>
    <th class="align-middle" scope="col">
      <%= t('.rule') %>
    </th>
    <th class="align-middle" scope="col">
      <%= t('.actions') %>
    </th>
  </tr>
  <%= render @badges %>
</table>

app/views/admin/badges/_form.erb
<label><%= form_badge_header(@badge) %></label>
<%= render 'shared/errors', resource: @badge %>
<%= form_with model: [:admin, @badge],
              local: true do |form| %>

  <%= form.label t('.name') %>
  <%= form.text_field :name %>
  <br/>

  <%= form.label t('.url') %>
  <%= form.text_field :url %>
  <br/>

  <%= form.label t('.description') %>
  <%= form.text_field :description %>
  <br/>

  <%= form.label t('.rule') %>
  <%= collection_check_boxes(:badge, :rule_ids, Rule.all, :id, :description,
                             include_hidden: false) do |b| %>
    <div>
      <%= b.check_box(checked: @badge.rules.include?(b.object)) %>
      <%= b.label %>
    </div>
  <% end %>
  <br/>

  <%= form.submit t('.submit') %>
  <%= link_to 'Back to all badges', admin_badges_path %>
<% end %>

app/views/admin/badges/edit.html.erb
<%= render 'form' %>

app/views/admin/badges/index.html.erb
<h1><%= t('.title') %></h1>
<%= link_to 'Create new badge', new_admin_badge_path %>
<%= render 'admin/badges/badges_table', resource: @badges %>

app/views/admin/badges/new.html.erb
<%= render 'form' %>

app/views/admin/badges/show.html.erb
<h1><%= t('.name') %>: <%= @badge.name %></h1>
<label>
  <%= t('.icon') %>: <%= image_tag(@badge.url, size: '25x25') %>
</label>
<br/>
<label><%= t('.description') %>: <%= @badge.description %></label>
<br/>
<label><%= t('.rule') %>: <%= print_badge_rules(@badge) %></label>
<br/>
<%= link_to t('.back'), admin_badges_path %>