config/routes.rb
Rails.application.routes.draw do
  get 'badges/index'
  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: {
               sessions: 'users/sessions', only: %i[create]
             }

  root to: 'tests#index'

  resources :feedback, only: %i[new create show]
  resources :badges, only: :index
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :badges
    resources :gists, only: %i[index]
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: %i[index] do
        resources :answers, shallow: true, except: %i[index]
      end
    end
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  MAX_ANSWERS = 4
  MIN_ANSWERS = 1

  belongs_to :question

  validate :validate_maximum_answers_count, on: :create
  validate :validate_answers_count, on: :update

  scope :correct, -> { where(correct: true) }

  private

  def validate_maximum_answers_count
    return unless question.answers.count >= MAX_ANSWERS

    errors.add :answer, "Maximum answers count should not be more than #{MAX_ANSWERS}"
  end

  def validate_answers_count
    @original_answer = Answer.find(id)

    return if question_id == @original_answer.question_id

    check_next_question_answers
    answers_count = question.answers.count

    return if answers_count > MIN_ANSWERS && answers_count < MAX_ANSWERS

    answer.errors.add :answer, "Answers count should not be less than #{MAX_ANSWERS}" if answers_count - 1 < MIN_ANSWERS
  end

  def check_next_question_answers
    next_answer_question = Question.find(question_id)
    next_question_answers_count = next_answer_question.answers.count

    return unless next_question_answers_count + 1 > MAX_ANSWERS

    answer.errors.add :answer, "Answer with id #{next_answer_question.id} will have more than #{MAX_ANSWERS} allowed"
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :users_badges, dependent: :destroy
  has_many :users, through: :users_badges, dependent: :destroy
  has_many :badges_rules
  has_many :rules, through: :badges_rules

  validates :name, presence: true
  validates :url, presence: true
  validates :description, presence: true
end

app/models/badges_rule.rb
class BadgesRule < ApplicationRecord
  belongs_to :rule
  belongs_to :badge
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope -> { order(title: :desc) }

  has_many :tests, dependent: :destroy
  has_many :badges, dependent: :nullify

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :test_passages, dependent: :destroy, foreign_key: 'current_question_id'
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/rule.rb
class Rule < ApplicationRecord
  has_many :badges_rules
  has_many :badges, through: :badges_rules

  enum circumstance_variant: %i[
    all_within_category
    all_perfectly
    tests_passed_3
    tests_passed_5
    all_tests_done
    all_within_level
  ]

  validates :description, presence: true
  validates :circumstance, inclusion: { in: circumstance_variants.keys.map(&:to_s) }
  validates :value, numericality: { only_integer: true, greater_than: 0}
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :completed_by, through: :test_passages, source: :user

  validates :title, presence: true
  validates :level, numericality: { only_integer: true, greater_than: 0 }
  validates :level, uniqueness: { scope: :title,  message: 'Test with same title and level already exists' }
  validates :time_limit, numericality: { only_integer: true, greater_than: 0 }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }

  class << self
    def by_category_title(category_title)
      joins(:category)
        .where({ categories: { title: category_title } })
        .order(title: :desc)
        .pluck(:title)
    end
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATIO = 0.85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_question, on: %i[create update]
  before_create :set_end_time

  class << self
    def user_passed_tests(user)
      where(user:)
        .order(:test_id)
        .select(&:passed?)
    end
  end

  def accept!(answer_ids)
    return if out_of_time?

    self.correct_questions += 1 if correct_answer?(answer_ids)

    save!
  end

  def question_number
    test.questions.order(:id).find_index(current_question) + 1
  end

  def completed?
    return false if new_record?
    return true if out_of_time?

    current_question.nil? && find_next_question.nil?
  end

  def passed?
    (correct_questions / test.questions.count) >= SUCCESS_RATIO
  end

  def perfectly?
    correct_questions == test.questions.count
  end

  private

  def out_of_time?
    end_time < Time.now
  end

  def set_end_time
    self.end_time = Time.now + test.time_limit.minutes
  end

  def find_next_question
    return test.questions.first if new_record?
    return nil unless current_question

    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def before_validation_set_question
    return unless test.present?

    self.current_question = find_next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable,
         :trackable

  has_many :users_badges, dependent: :destroy
  has_many :badges, through: :users_badges, source: :badge, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: 'Test', foreign_key: :author_id, dependent: :destroy
  has_many :completed_tests, through: :test_passages, source: :test, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true

  def completed_tests_by_level(level)
    completed_tests.where(level:)
  end

  def test_passage(test)
    test_passages
      .order(id: :desc)
      .find_by(test_id: test.id)
  end
end

app/models/users_badge.rb
class UsersBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
  def form_badge_header(badge)
    "#{badge.persisted? ? 'Edit' : 'Create new'} badge"
  end

  def print_badge_rules(badge)
    badge.rules
         .map(&:description)
         .join(', ')
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/gists_helper.rb
module GistsHelper
  def short_question_format(body)
    body.slice(0, 25)
  end
end

app/helpers/rules_helper.rb
module RulesHelper; end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  def form_test_header(test)
    test.persisted? ? "Edit #{test.title}" : 'Create new test'
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def flash_class_by_type(flash_type)
    case flash_type
    when 'notice' then 'warning'
    when 'alert' then 'danger'
    else 'primary'
    end
  end
end

app/views/admin/_navbar.erb
  <nav class="navbar bg-light">
    <div class="container justify-content-between">
          <div class="row nav">
            <div class="nav-item">
              <a class="nav-link active" href="<%= admin_tests_path %>">
                <h3>
                  <%= t('.title') %>
                </h3>
              </a>
            </div>
          </div>
          <div class="row">
            <span class="container justify-content-between">
              <% if user_signed_in? %>
              <span><%= t('.greeting', email: current_user.email) %></span>

                <%= link_to t('.gists'),
                              admin_gists_path,
                              type: :button,
                              method: :get,
                              class: 'btn btn-primary ml-4' %>

                <%= link_to t('.badges'),
                              admin_badges_path,
                              type: :button,
                              method: :get,
                              class: 'btn btn-primary ml-4' %>

                <%= button_to t('.logout'),
                              destroy_user_session_path,
                              method: :delete,
                              type: :button,
                              class: 'btn btn-primary ml-4' %>

              <% else %>
                <%= link_to t('.signin'), new_user_session_path, class: 'nav user' %>
                <%= link_to t('.signup'), new_user_registration_path %>
              <% end %>
            </span>
          </div>
        </div>
  </nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('.title') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="body">
    <%= render 'admin/navbar' %>
    <div class="container">
      <%= render 'shared/flash' %>

      <div class="row justify-content-center">
        <div class="col-md-5 col-8">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('.title') %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit-no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="body">
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <div class="row justify-content-center">
        <div class="col-md-5 col-8">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_errors.erb
<% if resource.present? && resource.errors.size > 0 %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id} do %>
    <p> <%= t('.header', count: resource.errors.size) %> </p>
    <ul>
      <% resource.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.erb
<% flash.each do |key, message| %>
  <p class="alert alert-<%= flash_class_by_type(key) %>" role="alert">
    <%= message.html_safe %>
  </p>
<% end %>

app/views/shared/_footer.erb
<footer style=";position: absolute;bottom: 0;margin-top: 50px;width: 100%">
  <p style="text-align: center">
    <%= github_url('Zakorko Alexander', 'test-guru') %>
    <span><%= t('.description') %></span>,
    <span><%= current_year %></span>
  </p>
</footer>

app/views/shared/_navbar.erb
  <nav class="navbar bg-light">
    <div class="row nav">
      <div class="nav-item">
        <a class="nav-link active" href="<%= user_signed_in? ? root_path : '#' %>">
          <h3>
            <%= t('.title') %>
          </h3>
        </a>
      </div>
    </div>

    <span class="row flex-direction-row">
      <% if user_signed_in? %>
        <span class="mr-5 mt-2">
          <%= t('.greeting', email: current_user.email) %>
        </span>
        <%= button_to 'My Badges',
                      badges_index_path,
                      method: :get,
                      class: 'btn btn-primary  mr-4' %>
        <%= button_to t('.feedback'),
                      new_feedback_path,
                      method: :get,
                      class: 'btn btn-primary  mr-4' %>
        <%= button_to t('.logout'),
                      destroy_user_session_path,
                      method: :delete,
                      class: 'btn btn-primary  mr-4' %>
      <% else %>
        <%= link_to t('.signin'), new_user_session_path, class: 'btn btn-primary  mr-4' %>
        <%= link_to t('.signup'), new_user_registration_path, class: 'btn btn-primary mr-4' %>
      <% end %>
    </span>
  </nav>

app/views/shared/_progress_bar.erb
<div class="progress-bar-container"
     data-current="<%= resource.current %>"
     data-total="<%= resource.total %>">
  <div class="progress-bar-indicator"></div>
</div>