config/routes.rb
Rails.application.routes.draw do
  get 'badges/index'
  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: {
               sessions: 'users/sessions', only: %i[create]
             }

  root to: 'tests#index'

  resources :feedback, only: %i[new create show]
  resources :badges, only: :index
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :badges
    resources :gists, only: %i[index]
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: %i[index] do
        resources :answers, shallow: true, except: %i[index]
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :test_passages, dependent: :destroy, foreign_key: 'current_question_id'
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATIO = 0.85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_question, on: %i[create update]
  before_create :set_end_time

  class << self
    def user_passed_tests(user)
      where(user:)
        .order(:test_id)
        .select(&:passed?)
    end
  end

  def accept!(answer_ids)
    return if out_of_time?

    self.correct_questions += 1 if correct_answer?(answer_ids)

    save!
  end

  def question_number
    test.questions.order(:id).find_index(current_question) + 1
  end

  def completed?
    return false if new_record?
    return true if out_of_time?

    current_question.nil? && find_next_question.nil?
  end

  def passed?
    (correct_questions / test.questions.count) >= SUCCESS_RATIO
  end

  def perfectly?
    correct_questions == test.questions.count
  end

  private

  def out_of_time?
    end_time < Time.now
  end

  def set_end_time
    self.end_time = Time.now + test.time_limit.minutes
  end

  def find_next_question
    return test.questions.first if new_record?
    return nil unless current_question

    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def before_validation_set_question
    return unless test.present?

    self.current_question = find_next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :set_test_passage, only: %i[show update result]
  after_action :set_end_time_cookie, only: %i[show update]

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      BadgeGiveoutService.new(@test_passage).give_available_badges
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def show; end

  def result; end

  private

  def set_end_time_cookie
    cookies[:end_time] = @test_passage.end_time.to_time.iso8601
  end

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def test_passage_progress(test_passage)
    question_index = test_passage.question_number - 1
    questions_total = test_passage.test.questions.count

    OpenStruct.new(current: question_index, total: questions_total)
  end
end

app/views/test_passages/result.erb
<h1><%= "#{t('.result') } #{@test_passage.test.title}:"%></h1>
<p>
  <% if @test_passage.passed? %>
    <span style="color: green"><%= t('.success') %></span>
  <% else %>
    <span style="color: red"><%= t('.fail') %></span>
  <% end %>
</p>
<p>
  <%= link_to t('.to_all_tests') ,tests_path %>
</p>

app/views/test_passages/show.erb
<h2><%= t('.test_passage') %> <%= @test_passage.test.title %> </h2>
<%= render 'shared/progress_bar', resource: test_passage_progress(@test_passage) %>
<p><%= t('.question_number', current: @test_passage.question_number, total: @test_passage.test.questions.count) %></p>
<p><%= @test_passage.current_question.body %></p>
<p>
  Time left: <span id='timer' style="color: red"></span>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, html: {name: :answer}, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids,
                                  @test_passage.current_question.answers,
                                  :id,
                                  :body,
                                  include_hidden: false do |check|  %>
    <p>
      <%= check.check_box id: "answer_ids_#{check.object.id}" %>
      <%= check.label %>
    </p>
  <% end %>
  <%= link_to t('.gist_question'), gists_path(@test_passage, test_passage: @test_passage.id), method: :post %>
  <br/>
  <%= form.submit t('.next') %>
<% end %>