config/routes.rb
Rails.application.routes.draw do
  get 'badges/index'
  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: {
               sessions: 'users/sessions', only: %i[create]
             }

  root to: 'tests#index'

  resources :feedback, only: %i[new create show]
  resources :badges, only: :index
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :badges
    resources :gists, only: %i[index]
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: %i[index] do
        resources :answers, shallow: true, except: %i[index]
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :test_passages, dependent: :destroy, foreign_key: 'current_question_id'
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_question, except: %i[create new]
  before_action :find_test, only: %i[create new]

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def create
    @question = @test.questions.build(question_params)

    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      render :show
    else
      render :edit
    end
  end

  def destroy
    @question.destroy

    redirect_to admin_test_path(@question.test)
  end

  def new
    @question = @test.questions.build
  end

  def show; end

  def edit; end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def record_not_found
    render plain: 'Entity not found', status: 404
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_question, except: %i[create new]
  before_action :find_test, only: %i[create new]

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def create
    @question = @test.questions.build(question_params)

    if @question.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      render :show
    else
      render :edit
    end
  end

  def destroy
    @question.destroy

    redirect_to test_path(@question.test)
  end

  def new
    @question = @test.questions.build
  end

  def show; end

  def edit; end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def record_not_found
    render plain: 'Entity not found', status: 404
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def form_question_header(question)
    "#{question.persisted? ? 'Edit' : 'Create'} new '#{question.test.title}' question"
  end
end

app/views/admin/questions/_form.erb
<label><%= form_question_header(@question) %></label>
<%= render 'shared/errors', resource: @question %>
<%= form_with model: [:admin, @test, @question],
              local: true do |form| %>
  <%= form.text_field :body %>
  <%= form.submit t('.submit') %>
<% end %>

app/views/admin/questions/_question.erb
<tr>
  <td>
    <%= question.body  %>
  </td>
  <td>
    <%= link_to t('.show'), admin_question_path(question) %>
    <%= link_to t('.edit'), edit_admin_question_path(question) %>
    <%= link_to t('.delete'),
                admin_question_path(question),
                method: :delete,
                data: {
                  confirm: t('.confirm')
                }    %>
  </td>
</tr>

app/views/admin/questions/_questions_table.erb
<% if resource.empty? %>
  <p><%= t('.no_questions') %></p>
<% else %>
  <p><%= t('.questions_count', count: pluralize(resource.count, 'question')) %></p>
<% end %>
<table>
  <tr>
    <th>
      <%= t('.questions') %>
    </th>
    <th>
      <%= t('.actions') %>
    </th>
  </tr>
  <%= render resource %>
</table>

app/views/admin/questions/edit.erb
<%= render 'form' %>

app/views/admin/questions/new.erb
<%= render 'form' %>

app/views/admin/questions/show.erb
<h3><%= t('.test') %> `<%= @question.test.title %>`</h3>
<div>
  <%= @question.body %>
</div>
<p><%= t('.answers') %></p>
<%= render @question.answers %>
<br/>

<%= link_to t('.create_new_answer'), new_admin_question_answer_path(@question)  %>
<%= link_to t('.back_to_test'), admin_test_path(@question.test)  %>